import { MaxBinaryHeap } from './MaxBinaryHeap';
const heap = new MaxBinaryHeap([]);
heap.insert(12);
heap.insert(1);
heap.insert(7);
heap.insert(2);
heap.insert(4);
heap.insert(13);
heap.insert(8);
heap.insert(33);
heap.insert(2109);
heap.insert(22);
heap.insert(22);
heap.insert(22);
heap.insert(22);
heap.insert(21);
heap.insert(2);
heap.insert(22);
heap.insert(22);
heap.insert(222);
heap.insert(22);
heap.insert(22);
heap.insert(100).print();
console.log('***************');
heap.extractMax();
heap.print();
